### ISSUE TITLE
Duplicate data when provisioning data via template

### ISSUE THREAD

**Issue by r998877** [SharePoint/PnP-Provisioning-Schema#129]
When provisioning a List Instance with data (<DataRows> element) duplicate data will be created in the list when the provisioning template is applied again and the list already exists in the target site.

Scenario: Sometimes you want to provision some sort of master data to a list (like Category, Country, ...) and you want to make this repetitive (means: apply the same template with data to a site several times). 

It would be beneficial if it can be configured per list instance that data is not added to the list again, if the list already contains the same data. This should be made configure, e.g. by specifying a column in the target list to check against. Example: If you have a country list and the Title column contains the country names then - by it's nature - the title column contains unique values. In this case I would configure the Title column of that list to check against to keep the ambiguity of country names.)

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. I've added the KeyColumn attribute to the DataRows element, together with the UpdateBehavior (Skip or Overwrite) attribute in order to instruct the engine about how to behave in case of an already existing item. It will shop up in the next schema version. I will close this item.
