### ISSUE TITLE
PNP Command "Get-PnPProvisioningTemplate" does not export 2010 Workflows 

### ISSUE THREAD

**Issue by Bestebreurtje** [SharePoint/PnP-Provisioning-Schema#156]
Hello,

The PNP command "Get-PnPProvisioningTemplate" of a SharePoint Online Site does not export 2010 Workflows but only 2013 Workflows. 

Is anyone familiar with this issue?

The reason why I use 2010 Workflows is because a 2013 Workflow cannot create a Documentset.

Kind Regards,

Jeroen Bestebreurtje

**Comment by abelunibo** [comment]
Same issue here, I think it is not supported. Have you find any workaround?

**Comment by Bestebreurtje** [comment]
Our workaround is an Event Receiver which starts a PowerShell command and create a Documentset. Unfortunately, I couldn’t use a designer Workflow for this case


Vriendelijke groet, kind regards,

bam_ict

Jeroen Bestebreurtje
Business Consultant DMS
BAM ICT Application Services

T +31 (0)6 50 65 52 93
E jeroen.bestebreurtje@bam.com<mailto:jeroen.bestebreurtje@bam.com>


[cid:image001.png@01D27BA2.D4D31F50]
Royal BAM Group nv
Runnenburg 9, 3981 AZ Bunnik, The Netherlands | P.O. Box 20, 3980 CA Bunnik
Trade Register 30058019  www.bam.com<http://www.bam.com>

Van: Abel Garcia [mailto:notifications@github.com]
Verzonden: maandag 30 januari 2017 23:05
Aan: SharePoint/PnP-Provisioning-Schema <PnP-Provisioning-Schema@noreply.github.com>
CC: Bestebreurtje, Jeroen <jeroen.bestebreurtje@bam.com>; Author <author@noreply.github.com>
Onderwerp: Re: [SharePoint/PnP-Provisioning-Schema] PNP Command "Get-PnPProvisioningTemplate" does not export 2010 Workflows (#156)


Same issue here, I think it is not supported. Have you find any workaround?

**Comment by VesaJuvonen** [comment]
This issue was moved to SharePoint/PnP-Sites-Core#1031

**Comment by VesaJuvonen** [comment]
Hi @Bestebreurtje and @abelunibo,
provisioning engine does not indeed currently support SP2010 workflow export and this has been more around lack of community contributions around this area, since implementation is dependent on the work we all do cross the community. This has though come up with now few times, so we are looking what we can do in the future around the PnP engine for this. Since this request is for the Core component and specifically for the provisioning schema, will relocate this issue to PnP-Sites-Core repository.
