### ISSUE TITLE
pnp:Directory does not support multi sub directorys

### ISSUE THREAD

**Issue by iiunknown** [SharePoint/PnP-Provisioning-Schema#162]
My config is in the blow：

```xml
<pnp:Directory Src=".\locales\en-US" Folder="{site}/SiteAssets/locales/en-US" Overwrite="true" Recursive="true" />
```
the folder structural is: 
![image](https://cloud.githubusercontent.com/assets/4693549/21922828/8c19ee8a-d9ab-11e6-98ee-7dc970d8e15c.png)

and get error: can not find path...
![image](https://cloud.githubusercontent.com/assets/4693549/21922849/b0fd2078-d9ab-11e6-984d-f9a4dbf806f7.png)

**Comment by VenkateshKadiri66** [comment]
@PaoloPia @VesaJuvonen I don't get what's the issue here and why you have marked it as next version ideas. I have multiple sub directories under a parent directory which I provsion under Style Library. It successfully works. Here's my sample node. 
`<pnp:Directory Src=".\Assets\StyleLibrary" Folder="Style Library" Overwrite="true" Recursive="true" />`

**Comment by VesaJuvonen** [comment]
Hi Venkatesh, We are looking into taking this also in the account in away that you could define the folder hierarchy directly in the template.

**Comment by VenkateshKadiri66** [comment]
I didn't get what do you mean by defining folder hierarchy in the template. Can you give sample directory node to illustrate that?

**Comment by iiunknown** [comment]
@VenkateshKadiri66 Did you try my case？Defining SharePoint folder hierarchy path string  in the template，you can upload multiple files but not support multiple folders from local. It looks like there have some error in Powershell  code base on results error, maybe it's a circular process issue I guess.

**Comment by PaoloPia** [comment]
Hi,
Thanks for waiting. By using the Recursive attribute you should be able to traverse the full folder hierarchy. If it doesn't happen, that's a bug of the engine. From a schema perspective there is no need to change the schema, in order to make this happen. Thus I will close this item and open another one in the PnP-Sites-Core repo, referencing this one. Thanks again.
