### ISSUE TITLE
How to insert a  CSS file using <pnp:Custom Action>

### ISSUE THREAD

**Issue by harinvp** [SharePoint/PnP-Provisioning-Schema#165]
How to insert a css file using the CustomAction?. Tried using the below. But it always inserting a script tag with reference to the css file!. Tried using script block as well. But it didn't work.

` <pnp:CustomAction Name="Custom CSS" Description="Custom CSS for Application" Group="SiteActions"  Location="ScriptLink" Title="Custom Css" Sequence="115"  ScriptSrc="~sitecollection/Style Library//CSS/Custom.css" Rights="0" Enabled="true"/>`

I am able to insert one css file to the site using AlternateCSS under websettings. But this does not holds good because I want to inject multiple css files.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is a request for help, rather than an issue. Thus, I would like to ask you to use the Microsoft Technical Communities site to get prompt answer. Nevertheless, in order to answer your question, you should embed the CSS file by using a JS embedded script. Otherwise, if you have just one CSS, you can leverage the AlternateCSS attribute of the WebSettings element. I will close this item.
