### ISSUE TITLE
Content Types Inheritance

### ISSUE THREAD

**Issue by rathnamvemula** [SharePoint/PnP-Provisioning-Schema#186]
Is it possible to create a new custom Content Type from existing custom Content Type using Provisioning Schema?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using PnP. In order to get a prompt answer to your questions, I suggest you to use the https://techcommunity.microsoft.com/ site instead of this issues list. Because this is not an issue I will close it. Nevertheless, about your question, yes it is possibile to inherit a content type from another, using exactly the same approach that you can use with classic SharePoint and Feature Framework.
