### ISSUE TITLE
Applying template with Apply-PnPProvisioningTemplate Error

### ISSUE THREAD

**Issue by angi1976** [SharePoint/PnP-Provisioning-Schema#187]
I have an error when trying to apply a template with powershell. Here's the context. I have a farm with SharePoint 2013. I installed the latest version of powershell commands. I'm trying to provision a team site  with a custom page that has a 2 columns layouts and inside each column, i want to add 2 web parts. All is provisioned correctly until it encounters this error.  Field or property "ZoneId" does not exist

The page is correctly provisioned but when i have this error all the rest is stopped. And i didn't find the cause of the error. Is it a schema error or something else ?

Here's a part of my template. And i took the sample from "ProvisioningSchema-2016-05.md". So nothing strange in my template.
<pnp:WebParts>
            <pnp:WebPart Column="1" Row="1" Title="Script Editor">
              <pnp:Contents>
                <webParts>
                </webPart>
                </webParts>
              </pnp:Contents>
            </pnp:WebPart>

I use the pnpCore Version=2.13.1703.0

Thank you

**Comment by mintxelas** [comment]
In my case it was an issue with PnP library versions. Although I was extracting an SP2013 template using SharePointPnPCore2013; to apply it in SP2016 I had to use SharePointPnPCore2016.

**Comment by PaoloPia** [comment]
Hi,
Thanks for using PnP. However, this repository is related to the PnP Provisioning Schema, while your issue looks more related to the engine, which is in the PnP-Sites-Core repository. Moreover, in order to have a prompt answer I suggest you to use the Microsoft Tech Community site (https://techcommunity.microsoft.com), instead of this. I will close this item and create another one in the PnP Sites Core repository, referencing this one.
