### ISSUE TITLE
Remove flag for CustomAction

### ISSUE THREAD

**Issue by JessKCan** [SharePoint/PnP-Provisioning-Schema#197]
hi,

can you please give an example of how to use the Remove flag for CustomAction? I tried it in many ways but it doesn't do anything.

Thanks,

**Comment by PaoloPia** [comment]
Hi,
You simply need to use Remove="true" and if it doens't work as expected, please file an issue in the PnP-Sites-Core repository. Moreover, in order to have a prompt answer I suggest you to use the Microsoft Tech Community site (https://techcommunity.microsoft.com), instead of this. I will close this item and create another one in the PnP Sites Core repository, referencing this one.
