### ISSUE TITLE
Required setting in Content Type reverting to Optional

### ISSUE THREAD

**Issue by prawnz** [SharePoint/PnP-Provisioning-Schema#307]
Anyone have this issue where Required settings for fields in Content Type reverts to Optional when content provisioning is re-ran?

**Comment by SKatzenberger** [comment]
This is an issue since a long time ago.
In my case the site content type definition is correct after several executions of "applytemplate", but on list instances the required and hidden attributes are "reset" after another run. Not sure if this only happens in site collections which aren't underneath a managed path.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
