### ISSUE TITLE
ContentTypeID attribute of ClientSidePage not provisioned

### ISSUE THREAD

**Issue by AnitaBoerboom** [SharePoint/PnP-Provisioning-Schema#375]
We are using:

* PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
I would like the ContentTypeID attribute to be provisioned when I deploy a ClientSidePage using PnP xml.

#### Observed Behavior
ContentTypeID is not set for ClientSidePages using
<pnp:ClientSidePage PageName="MyPage.aspx" PromoteAsNewsArticle="false" Overwrite="true" EnableComments="false" Title="My Page" ContentTypeID="0x0101009D1CB255DA76424F860D91F20E6C4118" Publish="true">

I expect the page to be a SitePage content type, but instead the content type is set to de default content type of the library, which is another one.

#### Question:
How can I deploy a ClientSidePage with the specified content type set?

**Comment by nateforsyth** [comment]
Hi @AnitaBoerboom I've been fighting with a similar issue since 6th December 2018 and have had Microsoft Support looking into it for us since then.

Our scenario is slightly different where we are using PnP PowerShell cmdlets to provision pages using the default Content Type.

We then change the default Content Type on the Library expecting it to only effect subsequent new pages.

The issue for us is that previously created pages with Content Type correctly applied automatically change that Content Type to the newly set default.

I've been told that our problem was highlighted years ago with on-prem SharePoint but it was not prioritised/fixed back then. Microsoft Support have told me this is very similar to your issue, in fact it was them whom gave me this link.

I've provided them with the template export of one of our Libraries and they've been able to replicate our issue on their end.

Would you like me to keep you updated on our progress?

**Comment by DariuS231** [comment]
Hi @AnitaBoerboom,

I had the same issue and the workaround for me was to specify the Content type in the FieldValues.

``` XML
<pnp:ClientSidePage PageName="PageName" PromoteAsNewsArticle="false" Overwrite="true" Publish="true" Layout="Article" EnableComments="true" Title="PageName" >
  <pnp:FieldValues>
    <pnp:FieldValue Key="ContentTypeId" Value="0x0101009D1CB255DA76424F860D91F20E6C411800F9BADEF9EAD7E043B06128BDAC1C9308" />
  </pnp:FieldValues>
</pnp:ClientSidePage>
```

Hope this helps.

**Comment by AnitaBoerboom** [comment]
@nateforsyth thank for the info, please keep me informed about this issue.
@DariuS231 unfortunately this doesn't work for me

**Comment by DariuS231** [comment]
@AnitaBoerboom how are you applying this template? Powershell?

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. We're aware of this behavior and we're working on it. However, this is the Schema repo and this issue is out of context here. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks.

**Comment by nateforsyth** [comment]
Hi @AnitaBoerboom 

We did end up receiving a work-around from the Microsoft rep, please read on. It may assist you in resolving your issue.

**Symptom:**

Modern site page content type changed automatically based on the default content type of Site Pages library. 

**Analysis:**

- Tried to capture the backend request based on time line to check what triggered the change of content type, but no related records. 
- Collect template of Site Pages library, could reproduce this issue then, and also found the content type will persist if we changed it in UI. 
- Submit request to PG, and got feedback that it’s by designed behavior. As the document has no content type property in it. 
- Tried to provision modern page with Add-PnPClientSidePage, and could reproduce this issue. This command has no any content type applied when provision a new page. 
- This issue only occurs when there are more than 1 Site Page based content types, the page provisioned with Add-PnPClientSidePage will follow the first Site Page content type by the content type order of Site Pages library. 

**Root Cause:**

Add-PnPClientPage command will not assign content type when provisioning a modern page, so the created page will follow the default content type of the Site Pages library. About the item without content type assigned, it will follow library default setting, this is expected behavior.

**Workaround:**

The currently workaround is to use CSOM to update the affected site page’s content type twice to make it persists. Here are the sample script:

```powershell         
Add-Type -Path "c:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.dll"
Add-Type -Path "c:\Program Files\Common Files\microsoft shared\Web Server Extensions\16\ISAPI\Microsoft.SharePoint.Client.Runtime.dll"
 
$siteUrl = "<site url>" 
$username = "<user account>"
$password = Read-Host -Prompt "Enter password" -AsSecureString
$ctx = New-Object Microsoft.SharePoint.Client.ClientContext($siteUrl) 
$credentials = New-Object Microsoft.SharePoint.Client.SharePointOnlineCredentials($username, $password)   
$ctx.Credentials = $credentials

$web=$ctx.Web
$lists=$web.Lists
$list=$lists.GetByTitle("Site Pages")
$ContentTypes = $list.ContentTypes

$ctx.Load($web)
$ctx.Load($lists)
$ctx.Load($list)
$ctx.Load($ContentTypes)
$ctx.ExecuteQuery()

# get Content Type ID for both of Porject Home Page and Project Site Page

$php=$ContentTypes | where {$_.Name -like "*Project Home Page*"}
$psp=$ContentTypes | where {$_.Name -like "*Project Site Page*"}
$ctx.Load($php)
$ctx.Load($psp)
$ctx.ExecuteQuery()

$PHPID=$php.StringId
$PSPID=$psp.StringId

#Get Home.aspx page item and get content type id for home.aspx page twice.

$cquery = New-Object Microsoft.SharePoint.Client.CamlQuery
$cquery.ViewXml="<View><Query><Where><Contains><FieldRef Name='Title'/><Value Type='Text'>home</Value></Contains></Where></Query></View>"
$items=$list.GetItems($cquery)
$ctx.Load($items)
$ctx.ExecuteQuery()

foreach ($item in $items)
{
    if($item["Title"] -eq "Home")
    {
        $item["ContentTypeId"]=$PSPID
        $item.Update()
        $ctx.ExecuteQuery()

        $item["ContentTypeId"]=$PHPID
        $item.Update()
        $ctx.ExecuteQuery()
    }
}
```

**Solution:**

Actually, the issue was caused by the PnP command Add-PnPClientPage, an issue has been submitted in GitHub at https://github.com/MicrosoftDocs/office-docs-powershell/issues/2921. Currently, there is no update for the PnP command issue.

@PaoloPia please feel free to close this again. I just wanted to provide what we'd received to Anita.
