### ISSUE TITLE
Get/Apply-PnPProvisioningTemplate does not seem to support term pin with children

### ISSUE THREAD

**Issue by jonathanhotono** [SharePoint/PnP-Provisioning-Schema#378]
I got an issue while trying to apply a source template that contains terms with pinned children. Is it possible to support pinned terms on the xml template?

Source tenant:
![image](https://user-images.githubusercontent.com/6864547/53775531-0cb61c00-3f47-11e9-86a4-3d92139bb65b.png)

Target tenant:
![image](https://user-images.githubusercontent.com/6864547/53775415-974a4b80-3f46-11e9-8171-3dec9023552e.png)

xml sample here:
https://gist.github.com/jonathanhotono/df22165e9fef007c2578c0cf3da9004f

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. At the schema level we already support the @IsPinned attribute. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? Thanks. I will close this item, because out of context.
