### ISSUE TITLE
DefaultColumnValue on folder still has no effect

### ISSUE THREAD

**Issue by nigel-dewar** [SharePoint/PnP-Provisioning-Schema#383]
Hi There,

Im using the following schema version,

<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2018/07/ProvisioningSchema">

I've got this going on in a list (which works fine creating the folder ) but it does not set the default column value

<pnp:Folder Name="Design Mgt">
pnp:DefaultColumnValues
<pnp:DefaultColumnValue Key="Engineering_x0020_Category" Value="06000 Design Management" />
</pnp:DefaultColumnValues>
</pnp:Folder>

I have a column which comes through with the Content Type assocated with the list, Ive tried 'Engineering Category' and 'Engineering_x0020_Category' to no avail.

The only way I can get defaults to set on a folder is to go through the UI like so

![image](https://user-images.githubusercontent.com/9402456/54171488-3252a080-44c6-11e9-8e31-705f83e9769b.png)

Am I missing something? Or have I completely mis-understood what is meant by DefaultColumnValues ?

cheers

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This is an engine related issue/request. Could you please insert this item, if still needed, in the PnP-Sites-Core repository (https://github.com/SharePoint/PnP-Sites-Core/issues/)? At the schema level, we support Default Columns definition. Maybe @wobba, who wrote that part of the engine, can double-check. Thanks. In the meantime, I will close this item, because out of context.

**Comment by wobba** [comment]
There is an issue on core on this.

**Comment by nigel-dewar** [comment]
Thank you, I logged a fresh issue on the site-core branch

cheers
