### ISSUE TITLE
Include View element in provisioning schema

### ISSUE THREAD

**Issue by DTGitRepository** [SharePoint/PnP-Provisioning-Schema#406]
Only views seems to be included and this doesn't detail the parameters for actually creating a view.
You can of course use the samples or get a template from an existing view but it would be nice to have the complete reference material available also.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The <pnp:Views/> element contains CAML views and not PnP schema related children elements. That's why we don't have documentation about that XML excerpt. The best thing to do is to export (with Get-PnPProvisioningTemplate) the views definitions, or to learn CAML and update the views schemas accordingly.
