### ISSUE TITLE
Missing Settings in pnp:WebSettings

### ISSUE THREAD

**Issue by czullu** [SharePoint/PnP-Provisioning-Schema#408]
To have more control over the behavior of a site after provisioning it would be great to have following attributes added to PnP:WebSettings

AllowDesigner="xsd:boolean"
AllowCreateDeclarativeWorkflow="xsd:boolean"
AllowSaveDeclarativeWorkflowAsTemplate="xsd:boolean"
AllowSavePublishDeclarativeWorkflow="xsd:boolean"
ExcludeFromOfflineClient="xsd:boolean"
MembersCanShare="xsd:boolean"
DisableFlows="xsd:boolean"
DisableAppViews="xsd:boolean"
HorizontalQuickLaunch="xsd:boolean"
SocialBarOnSitePagesDisabled="xsd:boolean"
WebCommentsOnSitePagesDisabled="xsd:boolean"
SearchScope="xsd:int"

As from a comment of Erwin - it might be better to add a dictionary since we can expect additional settings to apear - just like SearchScope for modern Search.

Since this would be for a future Schema - i'm not sure if a pull should be done to experimental or to 2019-03 - both feels wrong.

**Comment by PaoloPia** [comment]
Hi @czullu,
Thanks for your feedback. I just created a new SiteSettings element with the site collection scoped settings that you suggested, as well as I added some new attributes to the WebSettings element. We prefer to avoid dictionaries of properties, in order to keep the template more readable and fully typed. The changes will show up in schema 201909.
