### ISSUE TITLE
Add a Remove attribute to a ListInstance element

### ISSUE THREAD

**Issue by SpliceVW** [SharePoint/PnP-Provisioning-Schema#410]
Would be nice to be able to remove a ListInstance on an existing site, much like you can do with security principles, fields, custom actions, etc. My use case is a site created from the OOB team site template, where we'd want to remove the Shared Documents and Team Notebook that are auto-provisioned with the OOB team site template.

**Comment by PaoloPia** [comment]
Hi @SpliceVW,
Thanks for your contribution. Unfortunately, we cannot accept this proposal because we usually don't want to remove/un-provision content with the engine. There are just a few things that we support removal for, and usually are references in collections (content types from lists, fields from content types, users from groups) and not actual objects. We suggest you to hide the OOB lists that you don't want, rather than removing them, in particular, thinking about the Shared Documents library.
