### ISSUE TITLE
No SiteTemplate/WebTemplate attribute on SiteCollection and Site elements?

### ISSUE THREAD

**Issue by YannickRe** [SharePoint/PnP-Provisioning-Schema#67]
I'm trying to understand the Provisioning Schema, and if I do correctly this means the PNP Provisioning Engine currently implements the Templating part.
There are already some other elements defined which are not used in the PNP Provisioning Engine, like SiteCollection and Site.

We are currently trying to implement something based upon this schema, but are noticing that both pnp:SiteCollection and pnp:Site do not have an attribute to provide the initial OOTB SharePoint template. Any reason why these are not there?
The CSOM API's currently require to provide a template to base the initial creation on, so it was weird to find that no option to provide one is available in the schema

**Comment by VesaJuvonen** [comment]
We have been concentrating more on the extract / import scenarios in the past, rather than for defining the hierarchy, which does partly explains this, but you are absolutely correct on the requirement. Currently engine assumes that the site already exists when you are applying template for it, this means that the engine it self does not create the actual site current, it rather assumes that it's already there and created by the host, which is using the engine.

This would not be however sufficient model when we want to create hierarchies of sites, so we'll need to address this in the next release of the schema.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. This requirement has been addressed by the SiteTemplate attribute defined in the SiteAttributes attributeGroup.Thus, I will close this item.
